name: tests

on:
    pull_request:
        branches:
            - "*"

jobs:
    build:
        name: test
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v3
        
          - name: Set up go
            uses: actions/setup-go@v3
            with:
                go-version: "1.22.2"
            
          - name: Prepare dependencies
            run: |
                go mod download
            
          - name: Test code
            run: |
                go test -race

          - name: Install golangci-lint
            run: |
                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
    
          - name: Run golangci-lint
            run: |
                golangci-lint run



